version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql
    container_name: chatix-db
    environment:
      MYSQL_ROOT_PASSWORD: figaro
      MYSQL_DATABASE: ChatixDB
      MYSQL_USER: root
      MYSQL_PASSWORD: figaro
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql